backend:
  name: github
  repo: Samdersson/Catalogocuadros
  branch: main
  site_domain: catalogo-cuadros.netlify.app

media_folder: "imagenes"
public_folder: "imagenes"

collections:
  - name: "cuadros"
    label: "Catálogo de Cuadros"
    files:
      - file: "cuadros.json"
        label: "Lista de Cuadros"
        name: "cuadros_data"
        fields:
          - label: "Cuadros"
            name: "cuadros"
            widget: "list"
            fields:
              - { label: "ID Único", name: "id", widget: "string" }
              - { label: "Título del Cuadro", name: "titulo", widget: "string" }
              - { label: "Número de Piezas", name: "piezas", widget: "number", value_type: "int" }
              - { label: "Imagen Principal", name: "imagen", widget: "image" }
              
              
              - label: "Etiquetas / Categorías"
                name: "etiquetas"
                widget: "list"
                field: { label: "Etiqueta", name: "tag", widget: "string" }
                
              # Medidas y Precios
              - label: "Medidas y Precios"
                name: "medidas"
                widget: "list"
                fields:
                  - { label: "Tamaño (ej: 80 x 50 cm)", name: "tamano", widget: "string" }
                  - { label: "Precio ($)", name: "precio", widget: "number", value_type: "int" }
                  - { label: "Especificaciones", name: "especificaciones", widget: "string" }